FROM redhat/ubi9 
RUN dnf install nginx -y
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
LABEL maintainer="RAMANA REDDY" \
      version="1.0" \
      description="This is a sample Dockerfile for nginx on UBI9" \
      COURSE="Docker for Beginners" \
      AUTHOR="RAMANA REDDY" \   
      DURATION="2 hours" \
      TOPICS="Dockerfile, nginx, UBI9"

