FROM almalinux:latest
#ENTRYPOINT ["ping", "google.com"] #in the command we cant override the entrypoint instruction 
#but we can pass the arguments to the entrypoint instruction while running the container.
#CMD ["ping","google.com"] #in the command we can override the cmd instruction while running the container.
#for better results we can use both the instructions together in the same dockerfile.

CMD ["google.com"]
ENTRYPOINT ["ping"]